services:

  # service configuration for mongo database.
  mongo:

    restart: never
#  backup:
#    build:
#      context: .
#      dockerfile: Dockerfile.backup
#    volumes:
#      - ./mongo_backups:/backup
#    depends_on:
#      - mongo
#  # streamlit app configuration
  app:
    restart: never

  mongo-express:
    restart: never

  watchtower:
    entrypoint: sleep 86400
    command: sleep 86400
    restart: never
