services:

  # service configuration for mongo database.
  mongo:

    restart: never
  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    image: ghcr.io/buckler89/mongo-bk:latest
    volumes:
      - ./mongo_backups:/backup
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
#  # streamlit app configuration
  app:
    restart: never

  mongo-express:
    restart: never

  watchtower:
    entrypoint: sleep 86400
    command: sleep 86400
    restart: never
