services:

  # service configuration for mongo database.
  mongo:
    # see https://hub.docker.com/_/mongo/
#    image: mongo:5.0.26 # mongo 5.0+ requires a CPU with AVX2 support.
    image: mongo:4.4.17-focal
    ports:
     - "27017:27017"
    volumes:
      - ./mongo-local:/data/db
      - ./mongo_backups:/backup
#    command: [ "mongod", "--bind_ip_all" ]
    restart: always


  # streamlit app configuration
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/buckler89/big_food-app:latest
    container_name: big_food-app
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
#    command: streamlit run Home.py --server.port 8501
    command: /bin/bash -c "streamlit run Home.py --server.port 8501 & ngrok http --domain=${NGROK_DOMAIN}  8501 --oauth google --oauth-allow-email ${OAUTH_ALLOW_EMAIL}"
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    restart: always

  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    image: ghcr.io/buckler89/mongo-bk:latest
    volumes:
      - ./mongo_backups:/backup
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: big_food-app