services:

  # service configuration for mongo database.
  mongo:
    restart: no

  backup:
    restart: no

  # streamlit app configuration
  app:
    command: streamlit run Home.py --server.port 8501
    restart: no

  mongo-express:
    restart: no

#  watchtower:
#    entrypoint: sleep 86400
#    command: sleep 86400
#    restart: never
