services:

  # service configuration for mongo database.
  mongo:
    restart: no

  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    image: ghcr.io/buckler89/mongo-bk:latest
    volumes:
      - ./mongo_backups:/backup
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    restart: no

  # streamlit app configuration
  app:
    command: streamlit run Home.py --server.port 8501
    restart: no

  mongo-express:
    restart: no

#  watchtower:
#    entrypoint: sleep 86400
#    command: sleep 86400
#    restart: never
